### ISSUE TITLE
Running with Docker and the specified file path not found

### ISSUE THREAD

**Issue by goku54477** [fluencelabs/dev-rewards#12] opened 2024-02-29 07:29 UTC
I have tried multiple times and I am unable to generate the proof here as it always shows the Specified file does not exist. I have made sure the file path is right but still does not work

![image](https://github.com/fluencelabs/dev-rewards/assets/118243927/046747df-bd9d-486c-9dbe-ec209cbd2abe)

**Comment by 2855321556** [comment] 2024-02-29 10:28
> 我教你，付费咨询，5元

教下我哥们，我名字就是我qq联系方式，愿意付费

**Comment by elshan-eth** [comment] 2024-02-29 12:41
maybe you need to change the path to the keys in `-v` argument

`docker run -it --network none -v {your_path_to_ssh_keys):/root/.ssh dev-reward-script`

but inside docker, your path will be ` /root/.ssh/{your_key}`

**Comment by goku54477** [comment] 2024-02-29 13:44
Yes, I have passed the path of the ssh key in the argument and used `/root/.ssh/{your_key}` but still getting the same error
![image](https://github.com/fluencelabs/dev-rewards/assets/118243927/48016c01-eea9-4c3d-8d02-a68942bd917f)

**Comment by elshan-eth** [comment] 2024-02-29 17:18
Seems that docker doesn't see the path you specified.

**Comment by akim-bow** [comment] 2024-02-29 17:47
Try to use Windows path separators on the left side of `-v` command.

**Comment by goku54477** [comment] 2024-03-01 11:31
Hmm I have tried adding  the separators as well. The path is still not recognised

![image](https://github.com/fluencelabs/dev-rewards/assets/118243927/430d089c-e85a-423c-aee4-615472b4b8dd)

**Comment by akim-bow** [comment] 2024-03-04 08:28
Check the content of /root/.ssh by running `ls -la` command in docker, validate that your keys are there. I suppose you're entering path to the folder, not the path to the file with ssh keys, that's why path is incorrect. Pay attention to the mounted directory. Also i recommend reading docs/guides regarding mount volume page in docker guides. 

Anyway, seems like not an issue, i cannot reproduce it. Closing.

**Closed by akim-bow** 2024-03-04 08:28 UTC
