### ISSUE TITLE
remove SSH key requirement

### ISSUE THREAD

**Issue by paolofacchinetti** [fluencelabs/dev-rewards#49] opened 2024-03-07 17:38 UTC
There is no reason to require SSH keys only, thus excluding people that:
- have rotated SSH keys
- have been using Personal Access Tokens / GPG keys
- don't trust a script with their own SSH key (that might be used for more than just GitHub)

**Comment by akim-bow** [comment] 2024-03-07 18:55
Duplicate of #47

**Closed by akim-bow** 2024-03-07 18:55 UTC
